// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
	"github.com/vtdthang/kazan-gin-pg/order"
	"github.com/vtdthang/kazan-gin-pg/product"
)

import (
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

// Injectors from wire.go:

func InitProductAPI(db *gorm.DB) product.ProductAPI {
	productRepository := product.ProvideProductRepostiory(db)
	productService := product.ProvideProductService(productRepository)
	productAPI := product.ProvideProductAPI(productService)
	return productAPI
}

func InitOrderAPI(db *gorm.DB) order.OrderAPI {
	orderRepository := order.ProvideOrderRepository(db)
	orderSerive := order.ProvideOrderService(orderRepository)
	orderAPI := order.ProvideOrderAPI(orderSerive)
	return orderAPI
}
